### ISSUE TITLE
Link to github from npm website doesn't work

### ISSUE THREAD

**Issue by ntilwalli** [TylorS/cycle-router#2]
Hi, on npm it links to `cyclejs-router`, it should link to `cycle-router`.  I'd send a pull request but it also would require an `npm publish` which I can't do, so I just posted this.

**Comment by TylorS** [comment]
Thank you @ntilwalli I'll make the change soon

**Comment by TylorS** [comment]
Fixes with version 3.1.1. Thanks again!
