### ISSUE TITLE
Error using dot in url

### ISSUE THREAD

**Issue by carloslfu** [TylorS/cycle-router#4]
The example app in the readme.md don't runs with the dot in '/user/54.3' .
```
// Error
createLink('/user/54.3', 'User 54.3')
// This works
createLink('/user/543', 'User 543')
```

**Comment by TylorS** [comment]
I'll change it, however I don't really plan any further development on this library. I recommend moving to using HTTPS://github.com/tylors/cycle-history and HTTPS://github.com/staltz/switch-path. Used in conjunction they provide a much better and idiomatic Cycle experience.

**Comment by taylor1791** [comment]
Perhaps you should add that to the readme.

**Comment by TylorS** [comment]
@taylor1791 That is now in the README
